apiVersion: v1
kind: Service
metadata:
  name: noteapp-service
  namespace: noteappnamespace
spec:
  selector:
    app: noteapp
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP